version: "3.8"

services:
  postgres:
    container_name: givefree_db_postgres
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_MULTIPLE_DATABASES=$POSTGRES_MULTIPLE_DATABASES
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - "./pg/data:/var/lib/postgresql/data"
      - "./pg/init:/docker-entrypoint-initdb.d"
  web:
    depends_on:
      - postgres
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/givefree-api
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
